---
platform: linux

image_resource:
  type: registry-image
  source: { repository: hashicorp/terraform}

inputs:
  - name: source-code

params:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
  AWS_REGION: eu-west-1

run:
  path: sh
  args:
  - -exc
  - |
    terraform version
    cd source-code/infra/aws
    terraform init -upgrade=true
    terraform plan -var "aws_access_key=${AWS_ACCESS_KEY}" -var "aws_secret_key=${AWS_SECRET_KEY}" -var "aws_region=${AWS_REGION}"
    terraform apply -auto-approve  -var "aws_access_key=${AWS_ACCESS_KEY}" -var "aws_secret_key=${AWS_SECRET_KEY}" -var "aws_region=${AWS_REGION}"