---
platform: linux

image_resource:
  type: registry-image
  source: { repository: hashicorp/terraform}

inputs:
  - name: source-code

params:
  AWS_ACCESS_KEY:
  AWS_SECRET_KEY:
  AWS_REGION: eu-west-1

run:
  path: sh
  args:
  - -exc
  - |
    terraform version
    export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY}"
    export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_KEY}"
    pwd
    cd source-code
    terraform init -upgrade=true
    terraform fmt
    terraform validate