---
resources:
- name: source-code
  type: git
  icon: github
  source:
    uri: https://github.com/codigube/blouger.git
    branch: master
    paths:
      - infra/aws/*

jobs:
  - name: terraform-job
    plan:
      - get: source-code
        trigger: true
      - task: validate-tf          
        file: source-code/.ci/tasks/tf-validate.yml
        input_mapping: { source-code: source-code }
        params:
          AWS_ACCESS_KEY: ((aws_access_key))
          AWS_SECRET_KEY: ((aws_secret_key))
      - task: plan-tf
        file: source-code/.ci/tasks/tf-plan.yml
        input_mapping: { source-code: source-code }
        params:
          AWS_ACCESS_KEY: ((aws_access_key))
          AWS_SECRET_KEY: ((aws_secret_key))